### ISSUE TITLE
Qual o valor queremos entregar para as crianças?

### ISSUE THREAD

**Issue by regisgiongo** [kombrain/kickoff#1]

**Comment by jonathanbeber** [comment]
Eu gostaria muito de despertar o interesse de crianças para área de tecnologia, fazer com que elas se sintam interessadas e pensem nisso como um futuro.

Não sei se essa descrição pode ser clara como "valor que queremos entregar", mas seria algo em torno disso, aceito sugestões para iniciarmos um documento e trabalhar com pull requests de melhorias nele.

**Comment by regisgiongo** [comment]
Concordo contigo.

Valor que gostaria de entregar é despertar a paixão delas pela área de tecnologia mesmo.
Acho que através da programação é uma boa ideia pra despertar isso.

Vamos precisar montar um documento mesmo, até porque fica mais fácil para "vender" o projeto para escolas entender o valor disso.

**Comment by jonathanbeber** [comment]
Fechamos o valor como **Despertar paixão por tecnologia**, assim mantemos a cultura [KISS](https://pt.wikipedia.org/wiki/Keep_It_Simple) no projeto também.
