### ISSUE TITLE
Qual a faixa etária que vamos trabalhar?

### ISSUE THREAD

**Issue by regisgiongo** [kombrain/kickoff#2]

**Comment by jonathanbeber** [comment]
Pensei em 12 até 17 anos, por ser uma fase muito decisiva na vida, não tenho especialidade nisso, mas é a fase que me lembro de ter que tomar muitas decisões :smile:

**Comment by regisgiongo** [comment]
Então, eu estava pensando aqui...

Com 12 anos eu estava na sétima série na escola. É uma faixa boa.
Mas acho que poderíamos ter **dois focos** de curso. 
Um de **quinta a oitava série** e outro de **ensino médio**, faz sentido?
@jonathanbeber

**Comment by jonathanbeber** [comment]
@regisgiongo faz sim, acredito ser uma fase com muita mudança, a mesma pessoa muda muito pelo fator ensino médio. Martelamos em dois públicos alvos, com dois formatos de cursos diferentes.

**Comment by jonathanbeber** [comment]
Reabrindo a issue até termos algum documento que comente sobre essa decisão!
