### ISSUE TITLE
Vamos ensinar elas a programar? Online ou presencial?

### ISSUE THREAD

**Issue by regisgiongo** [kombrain/kickoff#3]

**Comment by regisgiongo** [comment]
Acredito que a ideia presencial no início é a mais interessante. 
Entretanto, seria legal criar um blog com video aulas bem básicas para quem quer se aprofundar mais.
Outra coisa que pensei é nós usarmos alguma táctica de gamefication pra cativar eles, com prêmio, sei lá.
Abri uma discussões nessa tarefa #4. 

Focando no objetivo aqui:

Acho que ensinar coisas básicas e rápidas de programação é o primeiro passo.
Podemos bater o martelo em Python?  @jonathanbeber

**Comment by jonathanbeber** [comment]
Gosto muito da ideia de usar o python pela simplicidade e pelo sucesso de alguns projetos, como o [Python para zumbis](https://www.pycursos.com/python-para-zumbis/). Por mim fechamos na linguagem Python!

Não consigo definir o objetivo de "ensinar a programar" como algo certo. Gostaria de abranger algo mais como "desenvolver o interesse pela área de tecnologia".

**Comment by jonathanbeber** [comment]
Sobre a questão presencial ou online, gostaria que o ensino ficasse presencial em primeiro momento, logo em seguida criaremos formas de disponibilizar mais material online, mas conseguimos chamar a atenção em primeiro momento e podemos repassar bons materiais online que já existem e conhecemos. De acordo, @regisgiongo?

**Comment by regisgiongo** [comment]
Fechou!
Também gostei do "Desenvolver o interesse pela área de tecnologia!"

Batemos o martelo então em...

```
Linguagem de início: Python
Modo de apresentação: Presencial
```

**Comment by jonathanbeber** [comment]
Okay, isso dará um esqueleto inicial para nosso documento de `quem somos nós?`. Vou deixar essa issue aberta para discutirmos se `vamos ensinar elas a programar?` ou discutimos isso na #1 com base no valor que queremos entregar?

**Comment by regisgiongo** [comment]
Com o documento da pra fechar essa também
